add rules for cases OCP-26848 OCP-26641
xueli181114/verification-tests pull request #32
Opened 2020-04-01 13:24 UTC by yuwang-RH

add rules for cases OCP-26848 OCP-26641

2020-04-01 13:24 UTC, yuwang-RH commented
@yasun1 @xueli181114 @tzhou5 Please help review this PR, Thanks.

2020-04-02 08:24 UTC, yasun1 commented
LGTM

2020-04-15 02:55 UTC, xueli181114 requested changes

2020-04-15 02:55 UTC, xueli181114 commented on lib/rules/web/ocm_console/dialogs_and_sidebar.xyaml
> +choose_loadbalancer_in_dialog:
How about control the `choose_loadbalancer_in_dialog` and `choose_persistent_quota_in_dialog` and node scale with one action and parameter. For example:
select_persistent_quota_in_dialog:
    action: click_persistent_quota_dropdown
    element:
        xpath: <xpath>
        op: click
scale_cluster:
  action: 
      if_para: persistent_quota_number
       ref: select_persistent_quota_in_dialog
  action: 
      if_param: <LB param>
      ref: choose_loadbalancer_in_dialog
...
  action: click_apply_button
  action: check_dialog_missing

2020-06-22 02:04 UTC, merged